//INTERFACE
export interface IAction {
    type: string,
    payload?: any
}

//CATEGORY
export const GET_CATEGORY_REQUEST = 'GET_CATEGORY_REQUEST'
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS'
export const GET_CATEGORY_ERROR = 'GET_CATEGORY_ERROR'

//POPULAR EVENTS
export const GET_POPULAR_EVENT_REQUEST = 'GET_POPULAR_EVENT_REQUEST'
export const GET_POPULAR_EVENT_SUCCESS = 'GET_POPULAR_EVENT_SUCCESS'
export const GET_POPULAR_EVENT_ERROR = 'GET_POPULAR_EVENT_ERROR'

//ALL EVENTS
export const GET_ALL_EVENT_REQUEST = 'GET_ALL_EVENT_REQUEST'
export const GET_ALL_EVENT_SUCCESS = 'GET_ALL_EVENT_SUCCESS'
export const GET_ALL_EVENT_ERROR = 'GET_ALL_EVENT_ERROR'
